### ISSUE TITLE
Layout 메뉴 선택 버그

### ISSUE THREAD

**Issue by vbalien** [6-6/CloudMind#1]
메뉴를 선택하고 캔버스의 허공을 클릭하게 되면 하이라이트가 사라짐

**Comment by vbalien** [comment]
이게 CSS의 focus로 배경색이 바뀌는거라 focus가 풀리면 하이라이트가 사라질수밖에 없네요..

**Comment by LoadIdentity** [comment]
넵 수정하겠습니다.
