### ISSUE TITLE
remove node  버그

### ISSUE THREAD

**Issue by ChorongJang** [6-6/CloudMind#15]
remove node  정상 삭제 되나 그 이후 root_list 받아오는 것이 안됨됨

ERR MSG
  File "/Users/chorong/Documents/project-cloudmind/CloudMind/cloudmind/restful/v1/root.py", line 16, in get
    if item.own_node.parent_node_id is None:
AttributeError: 'NoneType' object has no attribute 'parent_node_id'

**Comment by vbalien** [comment]
노드를 삭제할때 노드에 소속된 participant를 삭제하지 않아 발생한 이슈인것 같습니다.
