### ISSUE TITLE
leaf  다운로드 문제

### ISSUE THREAD

**Issue by kimjayney** [6-6/CloudMind#53]
jpg, pdf 등 다른 파일들은 파일 다운로드가 이상 없이 잘 되지만

png 파일 같은 경우 다운로드를 시도하려 할 때 빈 값으로 나옵니다. (다운로드가 되지 않습니다.)

**Comment by vbalien** [comment]
해당 문제는 한글파일 이름때문이며,
aee297ac80682a530bb271578cdafba60f737ac9 커밋에서 이미 해결된 문제였습니다. ~~

**Comment by kimjayney** [comment]
아아 방금 확인하였습니다~
